### ISSUE TITLE
Remove pinning to release

### ISSUE THREAD

**Issue by fabaff** [numat/productivity#27]
There is a release pinning for [pymod](https://github.com/numat/prodZctivity/blob/f25d1070df2c738c13ecca65137493eb4c164f27/setup.py#L259). This is block the RPM package from installation on Fedora as there is already pymodbus-2.4.0 shipped. The requirements should be softened. This will also cause issues if one is installing it in a venv with other packages that depends on pymodbus.

Thanks

**Comment by patrickfuller** [comment]
Thanks for the issue @fabaff!

Pymodbus has been pinned because of some instability between versions ([changing default endianness](https://github.com/riptideio/pymodbus/pull/71), [unexpected breaking dependencies](https://github.com/riptideio/pymodbus/issues/338), [using "async" as package name](https://github.com/riptideio/pymodbus/pull/345/files)). If we can get validation that this driver works with pymodbus 2.4.0, then I'm open to bumping the version. However, I doubt I'll be comfortable softening the version requirement entirely.

@JamesJeffryes - Do you mind taking a look?

**Comment by JamesJeffryes** [comment]
I've yet to find a way to reliably uncover breaking changes in industrial device communications (especially connection stability) short of manual testing with the hardware. That means that we will likely always be pinned to one release or another. It's a headache having conflicting requirements but elusive bugs are far worse. 

It's actually because we install this driver along with other packages like [clickplc](https://github.com/numat/clickplc/blob/master/setup.py#L25) [watlow](https://github.com/numat/watlow/blob/master/setup.py#L17)
and [midas](https://github.com/numat/midas/blob/master/setup.py#L19) that we are pinned to this particular version.  I could upload a release candidate to PyPI that's pinned to 2.4.0 if that's a help to you.

**Comment by alexrudd2** [comment]
The ProductivitySuite simulator is pretty flaky, crashes on various requests, and occasionally gives garbage data.  Could be 'good' enough to test in lieu of real hardware, albeit TCP/IP and not serial.

**Comment by alexrudd2** [comment]
https://github.com/riptideio/pymodbus/pull/531/commits/55bf3adfa368ec123f375d4f9970e6cc08d076ee both drops Python 3.5 support and renames some directories.

~from pymodbus.client.asynchronous.asyncio import ReconnectingAsyncioModbusTcpClient~

```
try:
    from pymodbus.client.asynchronous.async_io import ReconnectingAsyncioModbusTcpClient
except ModuleNotFoundError:
    from pymodbus.client.asynchronous.asyncio import ReconnectingAsyncioModbusTcpClient
```

**Comment by alexrudd2** [comment]
downstream fedora [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1892887)
