### ISSUE TITLE
Issues with the AOS32 datatype in the .csv file

### ISSUE THREAD

**Issue by WWhiteman** [numat/productivity#79]
Anytime I have any tags with type AOS32 in the .csv file I get thrown an error. I am able to read/write the analog outputs indirectly through secondary registers and a copy - but need to directly read analog output values.

> Traceback (most recent call last):
  File "/home/fert/src/Modbus/prod2000/numat/productivity.py", line 17, in <module>
    asyncio.run(modset())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/fert/src/Modbus/prod2000/numat/productivity.py", line 14, in modset
    async with ProductivityPLC(PLC_IP, CONFIG_PATH) as plc:
  File "/home/fert/src/Modbus/prod2000/numat/productivity/driver.py", line 43, in __init__
    self.addresses = self._calculate_addresses(self.tags)
  File "/home/fert/src/Modbus/prod2000/numat/productivity/driver.py", line 347, in _calculate_addresses
    raise ValueError(f"Only supporting an address span of 2000 {found_type}."
ValueError: Only supporting an address span of 2000 holding. If you need more, open a github issue at numat/productivity.

**Comment by alexrudd2** [comment]
Hello @WWhiteman; thank you for the report.

Can you please share the tags file you are using?

**Comment by WWhiteman** [comment]
Here is the tag file.

[tagsplz_basic.csv](https://github.com/numat/productivity/files/12538825/tagsplz_basic.csv)

**Comment by alexrudd2** [comment]
OK, I can confirm the problem:

Here are two example tags:
System ID | Tag Name | Retentive Mode | Initial Value | MODBUS Start Address | MODBUS End Address
-- | -- | -- | -- | -- | --
S32-000007 | Fert 1 Flow Meter Freq | FALSE | 0 | 428695 | 428696
AOS32-0.1.2.2 | AOS32-0.1.2.2 | FALSE | 0 | 416397 | 416398


Both the `S32` (signed 32-bit integer) and `AOS32` (signed 32-bit integer, analog output) are holding registers.
In other words, they are in the span `400001 - 465536` and read by function code `03`.

The driver attempts to read holding registers in blocks of 124 (125 is the max per request, per Modbus spec).  It will make multiple sequential requests to read the entire span of registers.  In this case, the span is (428695 - 416397) = 12298 registers, which would take ~100 requests.

12k registers / 100 requests seems excessive, so the driver throws the error you saw with a span of > 2000 registers.
https://github.com/numat/productivity/blob/29e51c01867e22c73fbfee930dce227fb76e2e89/productivity/driver.py#L345-L349

Changing that number `2000` to e.g. `20000` _should_ work as a workaround.  However, the driver is going probably going to be really slow with so many requests, so that wouldn't be my first choice.

**Can you change the registers to have a tighter span?**  For instance:

System ID | Tag Name | Retentive Mode | Initial Value | MODBUS Start Address | MODBUS End Address
-- | -- | -- | -- | -- | --
S32-000007 | Fert 1 Flow Meter Freq | FALSE | 0 | ~428695~ 416695 | ~428695~ 416696
AOS32-0.1.2.2 | AOS32-0.1.2.2 | FALSE | 0 | 416397 | 416398

**Comment by WWhiteman** [comment]
@alexrudd2 Thank you so much for the speedy response - I understand the system much better now. I am able to have full control of modbus addresses in this project so I simply moved them closer and everything seems to be functioning correctly.
